language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
sudo: required
install:
  - sudo apt-get remove mysql-common mysql-server-5.5 mysql-server-core-5.5 mysql-client-5.5 mysql-client-core-5.5
  - sudo apt-get autoremove
  - sudo apt-get install libaio1
  - wget -O mysql-5.6.24.deb http://dev.mysql.com/get/Downloads/MySQL-5.6/mysql-5.6.24-debian6.0-x86_64.deb/from/http://cdn.mysql.com/
  - sudo dpkg -i mysql-5.6.24.deb
  - sudo cp /opt/mysql/server-5.6/support-files/mysql.server /etc/init.d/mysql.server
  - sudo ln -s /opt/mysql/server-5.6/bin/* /usr/bin/
  - sudo sed -i'' 's/table_cache/table_open_cache/' /etc/mysql/my.cnf
  - sudo sed -i'' 's/log_slow_queries/slow_query_log/' /etc/mysql/my.cnf
  - sudo sed -i'' 's/basedir[^=]\+=.*$/basedir = \/opt\/mysql\/server-5.6/' /etc/mysql/my.cnf
  - bundle install --jobs=3 --retry=3 --deployment
before_script:
  - sudo /etc/init.d/mysql.server start
  - mysql --version
  - mysql -e "CREATE DATABASE IF NOT EXISTS tabular_test" -uroot
  - mysql -e "CREATE USER 'tabular_test'@'localhost' IDENTIFIED BY 'tabular_test';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON tabular_test.* TO 'tabular_test'@'localhost';" -uroot
script: RACK_ENV=test bundle exec rake db:migrate default
