language: ruby
rvm:
  - 2.0.0
  - 2.1.6
  - 2.2.2
before_script:
  - mysql --version
  - mysql -e "CREATE DATABASE IF NOT EXISTS tabular_test" -uroot
  - mysql -e "CREATE USER 'tabular_test'@'localhost' IDENTIFIED BY 'tabular_test';" -uroot
  - mysql -e "GRANT ALL PRIVILEGES ON tabular_test.* TO 'tabular_test'@'localhost';" -uroot
script: RACK_ENV=test bundle exec rake db:migrate default
